# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

minReadySeconds: 5
preStopSleepSeconds: 5
networkTester:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/k8s-network-tester
    tag: latest

app:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/http-gateway

  resources:
    requests:
      cpu: 0.01
      memory: 50Mi
    limits:
      memory: 100Mi

  httpClient:
    timeout: 5 # seconds

env:
  RUST_LOG: info

clusterService:
  ports:
    http: 8080
