language: rust
cache:
  cargo: true
  directories:
    - ${HOME}/google-cloud-sdk/
matrix:
  include:
    - rust: nightly-2018-01-12
      env:
        - CLIPPY_VERSION=0.0.179
      before_script:
        - cargo install clippy --version $CLIPPY_VERSION || echo "installed"
      script:
        - cargo clippy -- -D clippy
    - rust: stable
      if: branch != master OR type != push
    - rust: stable
      if: branch = master AND type = push
      env:
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      after_success:
        - bash scripts/deploy-docs.sh
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --write-mode=diff
  - cargo build
  - cargo test
