language: rust
cache: cargo
matrix:
  include:
    - rust: nightly-2018-01-12
      env: # use env so updating versions causes cache invalidation
        - CLIPPY_VERSION=0.0.179
      before_script:
        - cargo install clippy --version $CLIPPY_VERSION || echo "installed"
      script:
        - cargo clippy -- -D clippy
    - rust: stable
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --write-mode=diff
        - cargo build
        - cargo test

