[mqtt]
uri = "mqtt://127.0.0.1:1883"

[web]
listen_addr = "127.0.0.1:8000"

[authn."iam.example.net"]
audience = "example.net"
algorithm = "HS256"
# key = "data/keys/iam.key.binary.sample"
key = "Cargo.lock"

[id]
label = "http-gateway"
audience = "example.net"
