[package]
name = "http-gateway"
version = "0.1.0"
authors = ["Artem Tolpekin <a.tolpekin@netology-group.ru>"]

[dependencies]
futures = "0.1"
env_logger = "0.5"
log = "0.4"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bytes = "0.4"

actix = "0.5"
actix-web = "0.5"

paho-mqtt = { path = "vendor/paho.mqtt.rust" }

num_cpus = "1.8"
failure = "0.1"

