apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
    - image: netologygroup/http-gateway
      context: .
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - k8s/*
