apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: foxford/http-gateway
    context: .
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  helm:
    releases:
      - name: http-gateway
        chartPath: chart
        artifactOverrides:
          app.image: foxford/http-gateway
        imageStrategy:
          helm: {}
        valuesFiles:
          - deploy/values.yaml
