apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
    - image: netologygroup/http-gateway
      context: .
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
deploy:
  kustomize:
    paths:
    - deploy/k8s/overlays/ns
