apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: netologygroup/http-gateway
      context: .
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - deploy/k8s/http-gateway.yaml
      - deploy/k8s/http-gateway-config.yaml
      - deploy/k8s/http-gateway-environment.yaml
      - deploy/k8s/http-gateway-ingress.yaml
      - deploy/k8s/http-gateway-service.yaml
