apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "http-gateway.labels" . | nindent 4 }}
  name: {{ include "http-gateway.fullname" . }}-app
data:
  App.toml: |
    {{- $id :=  list (include "http-gateway.name" .) .Values.app.svc.audience | compact | join "." }}
    id = {{ $id | quote }}

    [mqtt]
    uri = "tcp://mqtt-gateway-cluster:51883"
    clean_session = false
    incoming_message_queue_size = 1000000
    outgoing_message_queue_size = 1000000
    reconnect_interval = 3
    keep_alive = 15

    [http]
    listener_address = "0.0.0.0:8080"

    [http.cors]
    allow_origins = "*"
    max_age = 86400

    [http_client]
    timeout = {{ .Values.app.httpClient.timeout }}

    [sentry]
    dsn = {{ .Values.app.sentryDsn | quote }}
    environment = {{ regexSplit "-" .Release.Namespace -1 | first | quote }}

    ##
    ## SVC
    ##
    [id_token]
    algorithm = {{ .Values.app.svc.algorithm | quote }}
    key = "data/keys/svc.private_key.p8.der"

    {{- printf "\n" }}
    {{- range .Values.app.audiences }}
    ##
    ## {{ .audience }}
    ##
    {{- $tenantServiceAudience := include "http-gateway.tenantServiceAudience" .audience }}
    {{- $tenantUserAudience := include "http-gateway.tenantUserAudience" .audience }}
    {{- $tenantObjectAudience := "" }}
    {{- if regexMatch "(?:talenttech)" .audience }}
    {{- $tenantObjectAudience = regexReplaceAll "(^(?:staging|testing)[\\d]*)" (include "http-gateway.tenantObjectAudience" (list $.Release.Namespace .audience)) "beta" }}
    {{- else }}
    {{- $tenantObjectAudience = include "http-gateway.tenantObjectAudience" (list $.Release.Namespace .audience) }}
    {{- end }}
    [authn.{{ list "iam" $tenantServiceAudience | join "." | quote }}]
    audience = [{{ $tenantServiceAudience | quote }}, {{ $tenantUserAudience | quote }}]
    algorithm = "ES256"
    key = {{ .authn.key | quote }}

    {{- printf "\n" }}
    [events.{{ $tenantObjectAudience | quote }}]
    callback = {{ .eventCallback | quote }}

    {{- printf "\n" }}
    {{- range .sources }}
    [[events.{{ $tenantObjectAudience | quote }}.sources]]
    account_id = {{ list .source $.Values.app.svc.audience | join "." | quote }}
    version = {{ .version | quote }}
    {{- printf "\n" }}
    {{- end }}
    {{- end }}
