apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "http-gateway.fullname" . }}
  labels:
    {{- include "http-gateway.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "http-gateway.selectorLabels" . | nindent 6 }}
