apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-gateway.fullname" . }}-cluster
spec:
  selector:
    {{- include "http-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.clusterService.ports.http }}
      targetPort: 8080
      name: http
